# Database configuration for testing and local development.
# First start with the secret values
---
apiVersion: v1
kind: Secret
metadata:
  name: torrent-social-mysql-credentials
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_USER: "${DB_USER}"
  DB_PASS: "${DB_PASS}"
  DB_NAME: "${DB_NAME}"
  DB_ROOT_PW: "${DB_ROOT_PW}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [client]
    default-character-set=utf8mb4

    [mysql]
    default-character-set=utf8mb4

    [mysqld]
    bind-address = 0.0.0.0
    collation-server = utf8mb4_unicode_520_ci
    init-connect='SET NAMES utf8mb4'
    character-set-server = utf8mb4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DB_HOST}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${DB_HOST}
  template:
    metadata:
      labels:
        app: ${DB_HOST}
    spec:
      volumes:
        - name: mysql-storage
          emptyDir: {}
        - name: mysql-config-volume
          configMap:
            name: mysql-config
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: torrent-social-mysql-credentials
                key: DB_ROOT_PW
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: torrent-social-mysql-credentials
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: torrent-social-mysql-credentials
                key: DB_PASS
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: torrent-social-mysql-credentials
                key: DB_NAME
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
          - name: mysql-config-volume
            mountPath: /etc/mysql/conf.d
---
apiVersion: v1
kind: Service
metadata:
  name: ${DB_HOST}
spec:
  selector:
    app: ${DB_HOST}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort