openapi: 3.0.0
info:
  version: 0.0.1
  title: Torrent Social API
  description: The API for Torrent Social.
paths:
  /posts:
    get:
      summary: List all posts
      responses:
        '200':
          description: A JSON array of post names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
