# This is the main kubernetes manifest file for the local development environment.
# Standing up this stack will create the whole website, database, and other services.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent-social
  labels:
    app: torrent-social
spec:
  replicas: 2
  selector:
    matchLabels:
      app: torrent-social
  template:
    metadata:
      labels:
        app: torrent-social
    spec:
      containers:
      - name: torrent-social
        image: ${TORRENT_SOCIAL_APP_IMAGE}
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-social-service
spec:
  selector:
    app: torrent-social
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
# DB service for local development and testing only
#${MYSQL_DB_K8S_MANIFEST}