# This is the main kubernetes manifest file for the local development environment.
# Standing up this stack will create the whole website, database, and other services.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent-social
  labels:
    app: torrent-social
spec:
  replicas: 2
  selector:
    matchLabels:
      app: torrent-social
  template:
    metadata:
      labels:
        app: torrent-social
    spec:
      containers:
      - name: torrent-social
        image: ${TORRENT_SOCIAL_APP_IMAGE}
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: WORKER_THREADS
            value: "4"
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: torrent-social-mysql-credentials
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: torrent-social-mysql-credentials
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: torrent-social-mysql-credentials
                key: DB_PASS
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: torrent-social-mysql-credentials
                key: DB_NAME
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-social-service
spec:
  selector:
    app: torrent-social
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
# DB service for local development and testing only
#${MYSQL_DB_K8S_MANIFEST}